<script>
	export let item;
	console.log(item);
</script>

<h2>{item.title}</h2>
<div>{@html item.markup}</div>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut efficitur lorem. Suspendisse maximus, turpis vel viverra tempor, turpis quam ultrices tellus, quis scelerisque neque odio sed massa. Sed aliquet sem non dui bibendum volutpat. Fusce mattis dapibus libero vel lobortis. Pellentesque pulvinar sit amet ipsum in dapibus. Fusce eleifend, elit sollicitudin tristique dictum, sem lacus consectetur diam, vitae tincidunt odio arcu et leo. Ut erat nibh, pretium id vestibulum in, egestas sed erat. Nulla facilisi. Integer feugiat dignissim augue et ornare. Praesent facilisis vel lacus vitae rutrum. Mauris quis ligula facilisis, ullamcorper erat ut, hendrerit felis.</p>
